module.exports = {

    CREATE_TABLE : 'CREATE TABLE IF NOT EXISTS "DB2INST1"."FOOD_REVIEWS" (PRODUCT_ID VARCHAR(10),TIME DATE, RATING SMALLINT, SENTIMENT_SCORE decimal(12,6), SENTIMENT_LABEL VARCHAR(8), SUMMARY varchar(120))',
    INSERT_TO_TABLE : 'INSERT INTO  "DB2INST1"."FOOD_REVIEWS" ("PRODUCT_ID","TIME","RATING","SENTIMENT_SCORE","SENTIMENT_LABEL","SUMMARY") VALUES(?, ?, ?, ?, ?, ?);'


}